server:
	interface: 127.0.0.1@5335
	access-control: 127.0.0.0/8 allow
	do-ip6: no
	harden-glue: yes
	harden-dnssec-stripped: yes
	qname-minimisation: yes
	aggressive-nsec: yes
	prefetch: yes
	prefetch-key: yes
	serve-expired: yes
	serve-expired-ttl: 86400
	serve-expired-reply-ttl: 30
	serve-expired-client-timeout: 1800
	hide-identity: yes
	hide-version: yes
	minimal-responses: yes
	edns-buffer-size: 1232
